In [1]:
#Question 1
#Part(a)
class Shape:
    def __init__(self, radius):
        self.radius = radius
    def calculate_area(self):
        return (3.142) * (self.radius ** 2) #Formula of area of a cricle = πr^2
    def calculate_perimeter(self):
        return 2 * 3.142 * self.radius      #Formula of perimeter of a circle = 2πr
class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius)
    def calculate_circumference(self):       #since perimeter and circumference of a circle are same
        return super().calculate_perimeter() # I inherited the perimeter function from parent class

radius = float(input("Enter the radius of the circle: "))
circle = Circle(radius)
print("Area of the circle: ", circle.calculate_area())
print("Circumference of the circle: ", circle.calculate_circumference())

Enter the radius of the circle: 23.4
Area of the circle:  1720.4335199999998
Circumference of the circle:  147.04559999999998


In [21]:
#Question 1
#Part(b)
class BankAccount:
    def __init__(self, starting_balance = 0.0):  #0 should be the starting balance, if not added
        self.balance = starting_balance
    def deposit(self, amount):
        print("\nStatus:")     #first showing the status of the amount
        print(f"Balance: {self.balance}Rs")     #then asking to deposit the amount
        print(f"Amount deposited: {amount}Rs\n")  #then displaying the actual amount deposited
        self.balance = self.balance + amount
        print("Status:")   #finally showing updated balance after deposit
        print(f"Balance after depositing: {self.balance}Rs.\n")
    def withdrawal(self, amount):
        if amount > self.balance:   #not possible if amount to be taken out is more than actual balance
            print("Insufficient balance. Cannot withdraw that much amount.\n")
            print("\nStatus:")
            print(f"Total Balance: {self.balance}Rs")
            print(f"Amount withdrawn: 0Rs\n")
        else:
            print("\nStatus:")   #else if smaller or equal than actual balance
            print(f"Balance: {self.balance}Rs")
            print(f"Amount withdrawn: {amount}Rs\n")
            self.balance = self.balance - amount    #amount will be withdrawn
            print("Status:")
            print(f"Balance after withdrawal: {self.balance}Rs\n")  #status after withdrawal

initial_balance = float(input("Enter the starting balance: "))
ba_Hamza = BankAccount(initial_balance)
while True:
    print("Menu:")
    print("1 Deposit")
    print("2 Withdrawal")
    print("0 Exit")
    choice = int(input("Enter your choice:"))
    if choice == 1:
        amount = float(input("Enter the amount you wnat to deposit: "))
        ba_Hamza.deposit(amount)
    elif choice == 2:
        amount = float(input("Enter the amount you want to withdraw:"))
        ba_Hamza.withdrawal(amount)
    elif choice == 0:
        print("Thanks for using our system. Allah Hafiz :)")
        break
    elif:
        print("Please enter the right option.\n")

Enter the starting balance: 2000
Menu:
1 Deposit
2 Withdrawal
0 Exit
Enter your choice:1
Enter the amount you wnat to deposit: 3000

Status:
Balance: 2000.0
Amount deposited: 3000.0

Status:
Balance after depositing: 5000.0.

Menu:
1 Deposit
2 Withdrawal
0 Exit
Enter your choice:2
Enter the amount you want to withdraw:5000

Status:
Balance: 5000.0
Amount withdrawn: 5000.0

Status:
Balance after wothdrawal: 0.0

Menu:
1 Deposit
2 Withdrawal
0 Exit
Enter your choice:0


In [3]:
#Question 1
#Part(c)
class Person:
    def __init__(self, name, age = None):   #if age isn't given None will be in age
        self.name = name
        self.age = age
    def __str__(self):    #using dender functions, because why not
        if self.age is None:  #if age is none, then Unknown shall be printed
            return f"Person: {self.name}\nAge: Unknown."
        else:                 #else actual info about a person i.e: name and age will be printed
            return f"Person: {self.name}\nAge: {self.age}"

while(True):
    name = str(input("Enter the name of the person: "))
    age = int(input("Enter the age: "))
    Guy = Person(name, int(age))
    print(Guy)
name = str(input("Enter the name of the person: "))
Second_guy = Person(name)
print(Second_guy)

Enter the name of the person: Hamza
Enter the age: 20
Person: Hamza
Age: 20
Enter the name of the person: Rasikh
Person: Rasikh
Age: Unknown.


In [4]:
#Question 1
#Part(d)
class Shape:
    def area(self):   #just a method named area for function overriding
        pass
class Rectangle(Shape):
    def __init__(self, length, width):
        self.length = length
        self.width = width
    def area(self):
        return self.length * self.width  #Formula of area of a rectangle = length * width
class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
    def area(self):
        return 3.142 * (radius ** 2)    #Formula of area of a cricle = πr^2

length = float(input("Enter the lenght: "))
width = float(input("Enter the width: "))
rectangle = Rectangle(length, width)
print("Area of rectangle:", rectangle.area())

radius = float(input("Enter the radius of the circle: "))
circle = Circle(radius)
print("Area of circle:", circle.area())

Enter the lenght: 76.2
Enter the width: 12.4
Area of rectangle: 944.8800000000001
Enter the radius of the circle: 23.134
Area of circle: 1681.541705752


In [24]:
#Question 2
class Vechile:
    def __init__(self, brand):
        self.brand = brand
    def info(self):    #function created for function overriding
        print(f"This is a {self.brand} vechile.")
class Car(Vechile):
    def __init__(self, brand):  #setting vechile name in the class
        super().__init__(brand)
    def engine_started(self):   #Engine started by inheriting vechile
        print(f"{self.brand}'s engine started.")
class Bicycle(Vechile):
    def pedal(self):   #didn't included a constructor because of brand name
        print(" bicycle peddling.")
class Hybrid(Car, Bicycle):
    def __init__(self, brand, fuel_type):
        Car.__init__(self, brand)
        Bicycle.__init__(self, brand)
        self.fuel_type = fuel_type
    def info(self):
        print("Status:")
        Vechile.info(self)
        print(f"It's a hybrid car.\n{self.brand}'s fuel type is {self.fuel_type}.")

car = str(input("Enter the name of the car: "))
toyota = Car(car)
bicycle = str(input("Enter the name of the bicycle: "))
BMX = Bicycle(bicycle)

toyota.engine_started()
print(bicycle, end = "")
BMX.pedal()
print("")
fuel_type = str(input(f"Enter the type of fuel for {car}: "))
print("")
hybrid_car = Hybrid(car, fuel_type)
hybrid_car.engine_started()
print(bicycle, end = "'s ")
hybrid_car.pedal()
hybrid_car.info()

Enter the name of the car: Toyota
Enter the name of the bicycle: BMX
Toyota's engine started.
BMX bicycle peddling.

Enter the type of fuel for Toyota: Petrol

Toyota's engine started.
BMX's  bicycle peddling.
Status:
This is a Toyota vechile.
It's a hybrid car.
Toyota's fuel type is Petrol.


In [25]:
#Question 3
#Part(a)
import numpy as np
array_20 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])  #array with 20 integers
print("Twenty elements array:", array_20)  #printing put the array
reshaped_4x5 = array_20.reshape(4,5)    #reshaping it into 4 rows and 5 columns
print("Reshaped arary:\n", reshaped_4x5)

Twenty elements array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshaped arary:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
#Question 3
#Part(b)
random_array_size = np.random.randint(0,10) #for total number of elements in the array
random_number_array = np.array(np.random.randint(1,101, size = random_array_size))  #creating an array between 1 and 100
print("Array:", random_number_array)
print("Maximum number in array:", random_number_array.max())   #printing max
print("Minimum number in array:", random_number_array.min())   #printing min

Array: [68]
Maximum number in array: 68
Minimum number in array: 68


In [8]:
#Question 3
#Part(c)
array = np.array([343,5,65,7,67,876,8,67,7,46])
greater_than_50 = array > 50   #masking elements greater than 50
print(array[greater_than_50])

[343  65  67 876  67]


In [9]:
#Question 3
#Part(d)
#Broadcasting in numpy allows us to bend the rules of array operations as we can perform element-wise
#operations without any replication of data. We just need to get the 'large dimension' of that thing right.

array_2d = np.array([[1,2,3],[4,5,6], [7,8,9]])
array_1d = np.array([[10,20,30]])
result_array = array_1d + array_2d
print(result_array)

#as you can see here, element-wise operations are performed one by one in a way that we use array with large 
#dimensions. As we can see [10,20,30] seperately adds up with [1,2,3],[4,5,6],[7,8,9]
#[1 + 10, 2 + 20, 3 + 30] = [11, 22, 33]
#[4 + 10, 5 + 20, 6 + 30] = [14, 25, 36]
#[7 + 10, 8 + 20, 9 + 30] = [17, 28, 39]

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [18]:
#Question 3
#Part(e)
new_array = np.array(array_20 ** 2)   #used same array of 20 integers and squared them
print(new_array)

[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]


In [11]:
#Question 4
#Part(a)
import pandas as pd
data = pd.read_csv("machine-readable-business-employment-data-jun-2023-quarter.csv")
print(data.head())  #head command used for dislaying first five cells of csv file

  Series_reference   Period  Data_value Suppressed STATUS
0      BDCQ.SEA1AA  2011.06     80078.0        NaN      F
1      BDCQ.SEA1AA  2011.09     78324.0        NaN      F
2      BDCQ.SEA1AA  2011.12     85850.0        NaN      F
3      BDCQ.SEA1AA  2012.03     90743.0        NaN      F
4      BDCQ.SEA1AA  2012.06     81780.0        NaN      F


In [19]:
#Question 4
#Part(b)
st_data = pd.read_csv("students data.csv")
print("Actual data:")
print(st_data)   #total data
mask = st_data[st_data["Age"] > 30]  #mask applied
print("\n\nData after filetering age grater than 30:")
print(mask)  #required data

Actual data:
       Name   Age   GPA
0      John  17.9  2.71
1      Jane  18.1  3.73
2     Sarah  17.6  2.64
3     Frank  32.1  3.68
4      Mike  18.2  3.46
5  Jennifer  35.0  4.24
6   Jessica  37.3   NaN
7      Fred  19.2  2.54
8       Bob  34.0  3.24


Data after filetering age grater than 30:
       Name   Age   GPA
3     Frank  32.1  3.68
5  Jennifer  35.0  4.24
6   Jessica  37.3   NaN
8       Bob  34.0  3.24


In [30]:
#Question 4
#Part(c)
store_data = pd.read_csv("100 Sales Records.csv")
total_sales = store_data.groupby("Region")["Sales"]  #grouping by region's sales
sum_of_total_sales = total_sales.sum()   #adding sales with the same region
print(sum_of_total_sales)

Region
Asia                                  59967
Australia and Oceania                 68325
Central America and the Caribbean     35771
Europe                                98117
Middle East and North Africa          48678
North America                         19143
Sub-Saharan Africa                   177503
Name: Sales, dtype: int64


In [2]:
#Question 4
#Part(d)
import pandas as pd
customer_data = pd.read_csv('Customer.csv')
customers_df = pd.DataFrame(customer_data)   #created one data frame with id's and names
print("Customer's data:\n", customers_df)
order_data = pd.read_csv('Order.csv')
orders_df = pd.DataFrame(order_data)   #created one data frame with order id's and customer's ids
print("\nCustomer's orders:\n", orders_df)
print("\nMerged data:\n",pd.merge(customers_df, orders_df))   #merging data

Customer's data:
    Customer ID    Customer Name
0         2012   Muhammad Hamza
1         2013  Muhammad Harris
2         2014          Khurram
3         2015            Basil

Customer's orders:
    Order ID  Customer ID
0        23         2012
1        34         2013
2        21         2014
3        24         2015

Merged data:
    Customer ID    Customer Name  Order ID
0         2012   Muhammad Hamza        23
1         2013  Muhammad Harris        34
2         2014          Khurram        21
3         2015            Basil        24
